### ISSUE TITLE
How to manage sagas with dynamic pages

### ISSUE THREAD

**Issue by michelalbers** [mxstbr/react-boilerplate#1487]
I know, I know this issue has been here multiple times (#390).

I'm building a social network with your react-boilerplate (which turns out to be pretty awesome by the way, keep up the good work! 👍 ) and I'm having some problems with fetching different kinds of posts. 

In my user profile there are 4 tabs:

* Everything
* Photos
* Videos
* Blogposts

Each click on a tab results in a ```this.props.dispatch(push('/profile/<tab>'))```.  Now ```injectAsyncSagas``` is called again resulting in duplicate sagas. This is known and you can work around it using:

```JavaScript
function fetchPostsSaga() {
   const watcher = yield fork(takeLatest, FETCH_POSTS, theActionHandler);
   yield take(LOCATION_CHANGE);
   yield cancel(watcher);
}
```
My problem now is a race condition. I dispatch the push event on a click of a Tab and after that I dispatch the FETCH_POSTS action. Unfortunetaly ```FETCH_POSTS``` is picked up BEFORE ```LOCATION_CHANGE``` fires. The result of that is that my saga is started and then cancelled immediately resulting in no posts being fetched.

I can fix it with wrapping the dispatch of the ```FETCH_POSTS``` action in a ```window.setTimeout(function() { /* ... */ }, 0)``` but that is just ugly.

What am I missing?

**Comment by adelsz** [comment]
This is one of the problems I addressed with an alternative saga life cycle in #1420.

**Comment by michelalbers** [comment]
@adelsz Just saw that. Its awesome, thank you so much 👍

**Comment by mxstbr** [comment]
@justingreenberg might want to chime in here about your specific problem. This should no longer a problem once we figure out a more clear way of handling saga lifecycles, (see #1384 for previous discussions) so I'll close this issue for now!

**Comment by cidevant** [comment]
> we figure out a more clear way of handling saga lifecycles

Which one? 

Still cant use route change and action dispatch in onClick handlers (functions)

```
dispatch(push({ ...location }));
dispatch(myAction());
```
Saga runs for n+1 times
