### ISSUE TITLE
Promise Error when creating route to a container

### ISSUE THREAD

**Issue by aslight21** [mxstbr/react-boilerplate#337]
I'm new to react and I decide to use this boilerplate for my first project. I don't know if this is a bug or if I need to link some things manually, but when I create a container and a route to this new container with the generator, I get an error when I try to access this container.

The error is the following:

```
es6.promise.js:119 Unhandled promise rejection ReferenceError: injectAsyncReducer is not defined
```

**Comment by EducatedTard** [comment]
same here

**Comment by mxstbr** [comment]
That's highly likely a bug with @justingreenberg's latest change. Lets see if we can fix it…

**Comment by mxstbr** [comment]
Ah nevermind, that was actually fixed in #323!

Change the `internals/templates/route/routeWithReducer.hbs` file, replacing `injectAsyncReducer` with `injectReducer` and `injectAsyncSaga` with `injectSaga` and it's going to work again—sorry for the troubles!

**Comment by aslight21** [comment]
This do not correct the problem entirely.

I got injectReducer is not define after the change. I saw that some line in the reducer.js where commented so I delete the // before these lines. This lead me to store is not define. I add store as a parameters to the create routes function and now I have two new errors:

Unhandle promise rejection type error: cannot read proprety equals of undefined 
and
Uncaught type error: reducer is not a function

...

**Comment by justingreenberg** [comment]
@aslight21 do not pass `store` to injectReducer—it is initialized with store in `getHooks`

**Comment by aslight21** [comment]
I don't, I change

export default function createRoutes() { ...
to
export default function createRoutes(store) { ..

**Comment by justingreenberg** [comment]
i'm sorry i'm not sure what you're talking about. with regard to the first error, please see:

https://github.com/mxstbr/react-boilerplate/blob/master/app/routes.js#L17
https://github.com/mxstbr/react-boilerplate/blob/master/app/routes.js#L33

**Comment by mxstbr** [comment]
I don't really know what the problem here is either, but it doesn't seem to be a problem with the boilerplate so I'll close this for now!

**Comment by mxstbr** [comment]
Ooops, didn't notice it was already closed. 🙊

**Comment by EducatedTard** [comment]
I have the same problem as @aslight21 ... When you create an empty project (with npm run clean), generate a container, generate a route, then assign the container to the route, the error pops up in the browser console when you are on the route. Now, I've made all the corrections you've mention above and I still have an error: es6.promise.js:119 Unhandled promise rejection TypeError: Cannot read property 'apply' of undefined(…)

This is straight up a plain project with a new container, route and the corrections you've mentioned. Am I doing something wrong or is there really an error somewhere?

**Comment by mxstbr** [comment]
Hmm, okay that's weird. I'll see if I can replicate that, sorry for the troubles!

**Comment by mxstbr** [comment]
Okay, I can replicate this, but I have no idea why that happens… Any clues?

**Comment by EducatedTard** [comment]
I'm pretty new to React so I don't really know ... This issue is kind of a problem since we can't create any new pages in our app until it is corrected. I want to use your boilerplate for my project, can you tell me a way to bypass this so i can route my app properly?

**Comment by ralomucho** [comment]
seems to be an error with  the container selector

**Comment by ralomucho** [comment]
supposing your container is MyCont

replace default  selectors.js  (in your container folder) with 

```
import { createSelector } from 'reselect';

const selectMyCont = () => state => state.get['MyCont']

export {
  selectMyCont,
};
```
and in your container index.js  replace your default export with
```
export default connect(createSelector(
  selectMyCont(), (mycont) => mycont
), mapDispatchToProps)(MyCont);
```

You'll got to adapt this with your own selectors

**Comment by ralomucho** [comment]
Ooops : replace 
```
const selectMyCont = () => state => state.get['MyCont']
```
with 
```
const selectMyCont = () => state => state.get['myCont']
```

**Comment by ralomucho** [comment]
this makes me see that template files are not enough complete to get something simple work out the box.
Mayb we should simplify them e.g. connect without createSelector.
I think every container should have a mapStateToProps, even it is  filled  with createSelector, the role of mapStateToProps is important to understand react-redux.
or put somme comments to clearly explain what to complete.
If the solution works for you, I'll do a PR.

**Comment by ralomucho** [comment]
Reooops:
replace
```
const selectMyCont = () => state => state.get['myCont']
```
with
```
const selectMyCont = () => state => state.get('myCont')
```

and 
```
export default connect(createSelector(
  selectMyCont(), (mycont) => mycont
), mapDispatchToProps)(MyCont);
```
with 
```
export default connect(createSelector(
  selectMyCont(), (mycont) => ({mycont})
), mapDispatchToProps)(MyCont);
```

**Comment by mxstbr** [comment]
Yeah that should work, would you mind submitting a PR @ralomucho?

**Comment by ralomucho** [comment]
ok !

**Comment by n4cr** [comment]
Thanks for the solution @ralomucho. I submitted the PR as others may already have problem with this: #352

**Comment by mxstbr** [comment]
Fixed by the amazing @n4cr in #352!

**Comment by jamesmbowler** [comment]
Is this fix live? I just pulled the project, and am getting this error.

**Comment by mxstbr** [comment]
This fix is live, we merged #352 and then #361 for the templates 5 days ago. Are you getting the same error?

**Comment by jamesmbowler** [comment]
Yeah

es6.promise.js:119 Unhandled promise rejection
ReferenceError: injectReducer is not defined(…)(anonymous function) @
es6.promise.js:119

**Comment by mxstbr** [comment]
Ah, you need to uncomment the `import` at the top of the file!

**Comment by jamesmbowler** [comment]
This import (in routes.js)?
import { getHooks } from 'utils/hooks';

I still get "injectReducer is not defined".

Then I uncomment this line (same file)

const { injectReducer, injectSagas } = getHooks(store);

and get "store is not defined".

**Comment by mxstbr** [comment]
Yeah, do those two things and then the `store` variable is passed into the `createRoutes` function. I.e. change it to this:

```
export default function createRoutes(store) {
```

**Comment by jamesmbowler** [comment]
That fixed it!

But there's another error, not sure if it's expected behavior, because i have not touched any of the files the script created.

main.js:19689 mapStateToProps() in Connect(Surveys) must return a plain object. Instead received Map {}.warning @ main.js:19689

**Comment by ralomucho** [comment]
you got to change the default selector of your component

```JS

/**
 * Default selector used by MyContainer
 */

const selectMyContainer = () => createSelector(
  selectMyContainerDomain(),
  (substate) => substate
);
```
substate is here an Immutable.Map and connect wants a plain object from mapStateToProps. That's why it's raises an error. Change to whatever you need.

By the way, I must fixed that to get no error with the default selector.

**Comment by holoiii** [comment]
@ralomucho What do you mean by changing the default selector? (I'm getting the same error as @jamesmbowler)

**Comment by mxstbr** [comment]
@holoiii yeah, that sounds reasonable! Would you mind submitting a PR for this?

**Comment by holoiii** [comment]
@mxstbr Sure thing - I'll get one out today

**Comment by jhedin** [comment]
So what exactly do I need to do to avoid this error now?

fix up routes.js, then fiddle with the selectors?

**Comment by ivnmaksimovic** [comment]
1. pulled repo
2. npm run setup
3. npm run clean
3. npm run generate container (let's call it "Surveys")
4. npm run generate route ("/surveys")
5. go to /surveys
6. see blank page with console error "ReferenceError: injectReducer is not defined"

1. go to app/routes.js
2. uncomment "import { getAsyncInjectors } from 'utils/asyncInjectors';"
3. uncomment "const { injectReducer, injectSagas } = getAsyncInjectors(store);"
4. add store to createRoutes "export default function createRoutes(store) {"

**Comment by gihrig** [comment]
I can confirm that @ivnmaksimovic's solution fixes the issue.

Is there a reason why that solution is not the default?

Would be happy to submit a PR.

**Comment by ivnmaksimovic** [comment]
I guess it is not there by default because you would not need it if you don't have containers with sagas on any route, which is unlikely.
