### ISSUE TITLE
Localhost with the port 3000 blocked

### ISSUE THREAD

**Issue by amorino** [mxstbr/react-boilerplate#94]
So, I installed this repo and ran it on the port 3000. Now every time I visit http://localhost:3000/ the application page load. I understand is the expected result because this is a offline-first React.js application but I cannot debug or hot-reload anything in that port even this example.

**Comment by mxstbr** [comment]
This is almost certainly a problem with your local setup. 

Nevertheless, this "bug" is fixed on the v3.0.0 branch, and cannot happen there. Check it out!

**Comment by amorino** [comment]
Thank you very much. I used lastest v3.0.0 (with the commit where you moved AppCache to production env.), I think the problem are the cookies, however is weird because I hard reload and clear cache and I still have the problem until I delete the File Data in Settings.

I think Google Chrome is the problem, I don't have problems using other browser so you are right, it is my local setup.

**Comment by mxstbr** [comment]
That's very weird, did you use master beforehand?

That might be why hot reloading isn't working, because Chrome still uses the master branch version (from cache) which connects to your v3.0.0 code base, which is a too major change for hot reloading.

**Comment by foxhound87** [comment]
@amorino I solved this in Chrome. Go to "chrome://serviceworker-internals" and "unregister" the app.

**Comment by mxstbr** [comment]
:+1: thanks @foxhound87!
